#!/usr/bin/env python3
"""Generate comparison plots for team clustering backends.

The script expects per-method metrics CSVs (kmeans, dbscan, cmeans) generated by
`run_team_classification_experiment.py`. It extracts the best accuracy for each
method overall and per crop_method, then saves bar charts for quick inspection.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt
import pandas as pd


DEFAULT_FILES = {
    "kmeans": Path("results/team_classification/numeric/team_classification_metrics_kmeans.csv"),
    "dbscan": Path("results/team_classification/numeric/team_classification_metrics_dbscan.csv"),
    "cmeans": Path("results/team_classification/numeric/team_classification_metrics_cmeans.csv"),
}


def load_metrics(files: Dict[str, Path]) -> pd.DataFrame:
    frames: List[pd.DataFrame] = []
    for method, path in files.items():
        if not path.is_file():
            continue
        df = pd.read_csv(path)
        df["method"] = method
        frames.append(df)
    if not frames:
        raise FileNotFoundError("No metrics CSVs found; run the experiments first.")
    return pd.concat(frames, ignore_index=True)


def best_overall(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.sort_values(["method", "accuracy"], ascending=[True, False])
        .groupby("method", as_index=False)
        .first()
    )


def best_per_crop(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.sort_values(["method", "crop_method", "accuracy"], ascending=[True, True, False])
        .groupby(["method", "crop_method"], as_index=False)
        .first()
    )


def plot_bar(df: pd.DataFrame, x: str, y: str, hue: str | None, title: str, out: Path) -> None:
    plt.figure(figsize=(6, 4))
    if hue:
        pivot = df.pivot(index=x, columns=hue, values=y)
        pivot.plot(kind="bar", ax=plt.gca())
    else:
        plt.bar(df[x], df[y])
    plt.ylabel("Accuracy")
    plt.ylim(0, 1)
    plt.title(title)
    plt.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot cluster method comparisons from metrics.")
    parser.add_argument("--kmeans", type=Path, default=DEFAULT_FILES["kmeans"])
    parser.add_argument("--dbscan", type=Path, default=DEFAULT_FILES["dbscan"])
    parser.add_argument("--cmeans", type=Path, default=DEFAULT_FILES["cmeans"])
    parser.add_argument("--output-dir", type=Path, default=Path("results/team_classification/plots/plots_cluster_methods"))
    args = parser.parse_args()

    files = {"kmeans": args.kmeans, "dbscan": args.dbscan, "cmeans": args.cmeans}
    metrics = load_metrics(files)

    overall = best_overall(metrics)
    per_crop = best_per_crop(metrics)

    plot_bar(
        overall,
        x="method",
        y="accuracy",
        hue=None,
        title="Best accuracy per clustering method",
        out=args.output_dir / "cluster_methods_overall.png",
    )
    plot_bar(
        per_crop,
        x="method",
        y="accuracy",
        hue="crop_method",
        title="Best accuracy per method and crop",
        out=args.output_dir / "cluster_methods_by_crop.png",
    )


if __name__ == "__main__":
    main()
